vim.keymap.set('n', '<C-s>', ':w<CR>', { desc = 'Save' })
vim.keymap.set('n', '<C-h>', '<C-w>h', { desc = 'Buffer left' })
vim.keymap.set('n', '<C-j>', '<C-w>j', { desc = 'Buffer down' })
vim.keymap.set('n', '<C-k>', '<C-w>k', { desc = 'Buffer up' })
vim.keymap.set('n', '<C-l>', '<C-w>l', { desc = 'Buffer right' })
vim.keymap.set('n', '<Leader>gg', function() require('snacks.lazygit').open() end, { desc = 'Toggle Lazygit' })
vim.keymap.set('n', '<Leader>e', function() require('snacks.explorer').open() end, { desc = 'Toggle explorer' })
vim.keymap.set('n', '<Leader>ff', function() require('snacks.picker').files() end, { desc = 'Find files' })
vim.keymap.set('n', '<Leader>fw', function() require('snacks.picker').grep() end, { desc = 'Find words' })
vim.keymap.set('n', '<Leader>a', ':Lspsaga code_action<CR>', { desc = 'Code action' })
vim.keymap.set('n', 'ge', ':Lspsaga diagnostic_jump_next<CR>', { desc = 'Next diagnostic' })
vim.keymap.set('n', 'gp', '<C-o>', { desc = 'Go previous' })
vim.keymap.set('n', '<S-h>', ':bprev<CR>', { desc = 'Previous buffer' })
vim.keymap.set('n', '<S-l>', ':bnext<CR>', { desc = 'Next buffer' })
vim.keymap.set('n', '<Leader>bc', ':bd<CR>', { desc = 'Close buffer' })
vim.keymap.set('n', '<Leader>bo', ':BufferLineCloseOthers<CR>', { desc = 'Close other buffers' })
vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { desc = "Run debug" })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { desc = "Step over" })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { desc = "Step into" })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { desc = "Step out" })
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end, { desc = "Toggle breakpoint" })
vim.keymap.set('n', '<Leader>B', function() require('dap').toggle_breakpoint() end, { desc = "Toggle breakpoint" })
vim.keymap.set('n', '<Leader>v', function() require('dapui').toggle() end, { desc = "Toggle debug UI" })
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', '<C-d>', '<C-d>zz')

vim.keymap.set('i', 'jk', '<Esc>')
vim.keymap.set('i', '<C-s>', ':w<CR>', { desc = 'Save' })

vim.keymap.set('x', 'p', 'pgvy', { desc = 'Improved paste' });
